env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 8
  sourceType: module
plugins:
  - sort-keys-fix
rules:
  no-var: error
  sort-keys-fix/sort-keys-fix: warn
