overrides:
  - files:
      - "*.css"
      - "*.js"
      - "*.jsx"
      - "*.less"
      - "*.overrides"
      - "*.scss"
      - "*.ts"
      - "*.tsx"
      - "*.variables"
    options:
      arrowParens: always
      singleQuote: true
      trailingComma: es5
      useTabs: true
  - files:
      - "*.json"
      - "*.yml"
    options:
      tabWidth: 2
